default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_development
  username: rails
  password: rails

test:
  <<: *default
  database: blog_test
  username: rails
  password: rails

production:
  <<: *default
  database: blog_production
  username: rails
  password: <%= ENV["BLOG_DATABASE_PASSWORD"] %>